eda_src/data/solution_files/chapter_18/ex_18_5_meal_planner/meal_plans/urls.py
"""Defines URL patterns for meal_plans."""

from django.urls import path

from . import views

app_name = 'meal_plans'
urlpatterns = [
    # Home page.
    path('', views.index, name='index'),
    # Page to view all meals.
    path('meals/', views.meals, name='meals'),
    # Page to view individual meals.
    path('meal/<int:meal_id>/', views.meal, name='meal'),
]

eda_src/data/solution_files/chapter_18/ex_18_5_meal_planner/mp_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meal_plans.urls')),
]

eda_src/data/solution_files/chapter_18/ex_18_5_meal_planner/meal_plans/models.py
from django.db import models

class Meal(models.Model):
    """An model for a single meal."""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the meal."""
        return self.name

class MealItem(models.Model):
    """An indidivual part of a meal."""
    name = models.CharField(max_length=200)
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the item."""
        return self.name 

eda_src/data/solution_files/chapter_18/ex_18_5_meal_planner/meal_plans/views.py
from django.shortcuts import render

from .models import Meal

def index(request):
    """The home page for Meal Planner."""
    return render(request, 'meal_plans/index.html')

def meals(request):
    """Page to show all available meals."""
    meals = Meal.objects.all()
    context = {'meals': meals}
    return render(request, 'meal_plans/meals.html', context)

def meal(request, meal_id):
    """Page to show an individual meal."""
    meal = Meal.objects.get(id=meal_id)
    meal_items = meal.mealitem_set.all()

    context = {'meal': meal, 'meal_items': meal_items}
    return render(request, 'meal_plans/meal.html', context)

eda_src/data/solution_files/chapter_18/ex_18_5_meal_planner/meal_plans/templates/meal_plans/base.html
<p>
  <a href="{% url 'meal_plans:index' %}">Meal Planner</a> -
  <a href="{% url 'meal_plans:meals' %}">Meals</a>
</p>

{% block content %}{% endblock content %}

eda_src/data/solution_files/chapter_18/ex_18_5_meal_planner/meal_plans/templates/meal_plans/index.html
{% extends 'meal_plans/base.html' %}

{% block content %}
  <p>Meal Planner helps you plan your meals for the week.</p>
{% endblock content %}

eda_src/data/solution_files/chapter_18/ex_18_5_meal_planner/meal_plans/templates/meal_plans/meal.html
{% extends 'meal_plans/base.html' %}

{% block content %}

  <p>Meal: {{ meal.name }}</p>

  <p>Meal Items:</p>
  <ul>
    {% for item in meal_items %}
      <li>{{ item.name }}</li>
    {% empty %}
      <li>No items have been added to this meal yet.</li>
    {% endfor %}
  </ul>
  
{% endblock content %}

eda_src/data/solution_files/chapter_18/ex_18_5_meal_planner/meal_plans/templates/meal_plans/meals.html
{% extends 'meal_plans/base.html' %}

{% block content %}

  <p>Meals</p>
  <ul>
    {% for meal in meals %}
      <li>
        <a href="{% url 'meal_plans:meal' meal.id %}">
          {{ meal.name }}</a>
      </li>
    {% empty %}
      <li>No meals have been added yet.</li>
    {% endfor %}
  </ul>

{% endblock content %}